
const ATTR_POSITION = 'ap'
const ATTR_NORMAL = 'an'
const ATTR_UV = 'au'

const U_MODELMATRIX = 'u1'
const U_VIEWMATRIX = 'u2'
const U_PROJECTIONMATRIX = 'u3'
const U_COLOR = 'u4'
const U_TIME = 'u5'
const U_TEXTURE = 'u6'
const U_TEXTURE_STARS = 'u7'
const U_GALAXY_CENTER = 'u8'
const U_SPACE_CENTER = 'u9'
const U_SPACE_CONNECTION = 'u10'
const U_WORLD_SIZE = 'u11'
const U_SPACE_POS = 'u12'
const U_VARIANT = 'u13'
const U_GALAXY_CONNECTION = 'u14'
const U_FADE_AMOUNT = 'u15'
const U_LOCKED = 'u16'
